services:
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    container_name: db

    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - net

  cache:
    image: redis:7.2.4-alpine
    restart: always
    container_name: cache
    networks:
      - net

  server:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - net
    container_name: server
    depends_on:
      - db
      - cache
    # command: alembic upgrade head

  client:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - net
    container_name: client

volumes:
  postgres_data:

networks:
  net:
    driver: bridge
