version: "3.9"

services:
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"

    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
